name: clean_redux
description: The package offers a structured way to implemet clean architecture with redux pattern
version: 0.3.3
repository: https://github.com/Oleh-Sv/clean_redux

environment:
  sdk: ^3.1.4

dependencies:
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  mocktail: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
