name: clean_redux
description: A starting point for Dart libraries or applications.
version: 0.1.1
repository: https://github.com/Oleh-Sv/clean_redux

environment:
  sdk: ^3.1.4

dependencies:
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7
  mocktail: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
